# Generated by Django 5.1.1 on 2024-09-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('vehiculo', models.CharField(max_length=10)),
                ('placa', models.CharField(max_length=10)),
            ],
        ),
    ]
