# Generated by Django 5.1.1 on 2025-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domiciliario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='placa',
            field=models.CharField(max_length=7),
        ),
    ]
