# Generated by Django 5.1.1 on 2024-09-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('arroz', 'Arroz'), ('combo', 'Combo')], max_length=10)),
                ('tamaño', models.CharField(choices=[('personal', 'Personal (400g)'), ('dos_personas', 'Para dos personas (700g)'), ('cuatro_personas', 'Para cuatro personas (1500g)'), ('seis_personas', 'Para seis personas (2500g)'), ('combo_familiar', 'Combo familiar + gaseosa 1.5L'), ('combo_personal', 'Combo personal + gaseosa + consomé')], max_length=20)),
            ],
        ),
    ]
