# Generated by Django 5.1.1 on 2025-02-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(max_length=50),
        ),
    ]
